### ISSUE TITLE
超级账本服务异常

### ISSUE THREAD

**Issue by Stark-X** [kaiyuanshe/kcoin#104]
## 截图
![image](https://user-images.githubusercontent.com/13653522/50679424-426d8000-103e-11e9-875a-b0fed1e14971.png)
![image](https://user-images.githubusercontent.com/13653522/50679436-4dc0ab80-103e-11e9-8951-ec2008437b1d.png)

## 描述
超级账本的服务有问题，线上打开页面 目前是NGINX 返回504 （另外这个地方暴露了nginx版本号以及Linux发行版），本地是500

**Comment by juniwang** [comment]
Fixed, please try again
