### ISSUE TITLE
how to test the addition interface in ruby?

### ISSUE THREAD

**Issue by MagicVin** [kaiyuanshe/kcoin#120]
I see the fabric_helpers.rb is about the chaincode invoked by ruby.
So if want to convert the chain code to ruby API, how to test it while the store is not supported yet.

**Comment by juniwang** [comment]
Using restapi client tool(rest console, postman or whatever you like) to test it against our Java API

**Comment by MagicVin** [comment]
Not very understand... :(

**Comment by MagicVin** [comment]
> Using restapi client tool(rest console, postman or whatever you like) to test it against our Java API

Not very understand :(

**Comment by MagicVin** [comment]
It works.
