### ISSUE TITLE
Test hyperledger failed 

### ISSUE THREAD

**Issue by MagicVin** [kaiyuanshe/kcoin#121]
I had double checked and the file is absolutely under the directory, but the terminal said that the file was lost.:

> file/home/vin/kcoin/src/server/target/classes/fabric/f21978d3b246501d0a16012a93d6bdc82985679d.peer/msp/keystore/4ad015b1-db94-ab28-b027-161c5b83376f_sk does not exist

Log clips:

> [INFO] Starting jetty 7.4.5.v20110725 ...
[INFO] jetty-7.4.5.v20110725
[INFO] No Transaction manager found - if your webapp requires one, please configure one.
[INFO] started o.m.j.p.JettyWebAppContext{/,file:/home/vin/kcoin/src/server/src/main/webapp/},file:/home/vin/kcoin/src/server/src/main/webapp/
[INFO] Started SelectChannelConnector@0.0.0.0:8080 STARTING
[INFO] Started Jetty Server
[INFO] Starting scanner at interval of 5 seconds.
received json：{"fn":"balance", "args":["symbol","owner"]}
Record as json：{"args":["symbol","owner"],"fn":"balance"}
org.hyperledger.fabric.sdk.exception.NetworkConfigurationException: Organization f21978d3b246501d0a16012a93d6bdc82985679d: adminPrivateKey file /home/vin/kcoin/src/server/target/classes/fabric/f21978d3b246501d0a16012a93d6bdc82985679d.peer/msp/keystore/4ad015b1-db94-ab28-b027-161c5b83376f_sk does not exist

**Comment by juniwang** [comment]
Can you double check whether the file exists in the folder `/home/vin/kcoin/src/server/target/classes/fabric/f21978d3b246501d0a16012a93d6bdc82985679d.peer/msp/keystore/4ad015b1-db94-ab28-b027-161c5b83376f_sk`? and please double check the certificates I sent you that the file exists. If not, I will send you again

**Comment by MagicVin** [comment]
> Can you double check whether the file exists in the folder `/home/vin/kcoin/src/server/target/classes/fabric/f21978d3b246501d0a16012a93d6bdc82985679d.peer/msp/keystore/4ad015b1-db94-ab28-b027-161c5b83376f_sk`? and please double check the certificates I sent you that the file exists. If not, I will send you again

It works after re-building the env ....  
No difference with the previous test env, it's so odd !!!
