### ISSUE TITLE
请问这个项目还在继续么？可还需要帮手？

### ISSUE THREAD

**Issue by sulenn** [kaiyuanshe/kcoin#134]
请问这个项目还在继续么？可还需要帮手？

**Comment by sulenn** [comment]
感觉有点要黄了的趋势，有很多功能都没有完成，并且已有的服务也存在问题。

**Comment by tedliu1** [comment]
非常欢迎你加入，就是因为功能还不完善才需要好手加入哦！请问你的微信号是什么，我将你和项目经理庄表伟拉一个小群，咱们可以先聊一聊哦！

Best regards,

Ted Liu, 
Co-founder & chairman of the board, KAIYUANSHE | ASF Member, Sponsor Ambassador, Incubator PMC Member 
 
  2019 年 10 月 4 日周五 10:20，俗人<notifications@github.com> 写道：   
感觉有点要黄了的趋势，有很多功能都没有完成，并且已有的服务也存在问题。

**Comment by sulenn** [comment]
17873588376
曾求兵




------------------ 原始邮件 ------------------
发件人: "Ted Liu"<notifications@github.com>; 
发送时间: 2019年10月4日(星期五) 上午10:30
收件人: "kaiyuanshe/kcoin"<kcoin@noreply.github.com>; 
抄送: "求兵"<273409891@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kaiyuanshe/kcoin] 请问这个项目还在继续么？可还需要帮手？ (#134)



非常欢迎你加入，就是因为功能还不完善才需要好手加入哦！请问你的微信号是什么，我将你和项目经理庄表伟拉一个小群，咱们可以先聊一聊哦！
 
 Best regards,
 
 Ted Liu, 
 Co-founder & chairman of the board, KAIYUANSHE | ASF Member, Sponsor Ambassador, Incubator PMC Member 
  
   2019 年 10 月 4 日周五 10:20，俗人<notifications@github.com> 写道：   
 感觉有点要黄了的趋势，有很多功能都没有完成，并且已有的服务也存在问题。

**Comment by think-in-universe** [comment]
hey guys, interested to meet the KCoin project here. 

I have researched and closely worked with several blockchain-based projects, and is interested to see how KCoin might work for Chinese community. 

I'm happy to chat about this and join the community. My telegram: https://t.me/robert_yan

**Comment by zhuangbiaowei** [comment]
@think-in-universe   请加我的微信号，也是@zhuangbiaowei
