### ISSUE TITLE
项目列表页的视觉问题

### ISSUE THREAD

**Issue by huzhengyu123** [kaiyuanshe/kcoin#28]
### **换成——60A8F0**
<img width="227" alt="image" src="https://user-images.githubusercontent.com/11845561/43493249-8fd793bc-955f-11e8-971a-a06e0440b543.png">

### **变更为红色——FF5C5D、FFD7D8**
<img width="983" alt="image" src="https://user-images.githubusercontent.com/11845561/43471051-a4f13e58-951c-11e8-921a-524a0b3977c9.png">

<img width="959" alt="image" src="https://user-images.githubusercontent.com/11845561/43471121-c9121e2e-951c-11e8-8bb3-b8f1b5d1a3ee.png">

![image](https://user-images.githubusercontent.com/11845561/43374151-c9fa5dca-93e0-11e8-9a27-a3872b99f141.png)

![image](https://user-images.githubusercontent.com/11845561/43374422-3ba3f246-93e2-11e8-80fe-4f0c310312a8.png)

![image](https://user-images.githubusercontent.com/11845561/43557544-abf20a90-9637-11e8-891e-032b3cbc6fb5.png)

![image](https://user-images.githubusercontent.com/11845561/43374191-034c5268-93e1-11e8-9669-5e500a9beb7e.png)

![image](https://user-images.githubusercontent.com/11845561/43374229-333c0ac2-93e1-11e8-840a-83ea63399c36.png)

![image](https://user-images.githubusercontent.com/11845561/43375184-0dba11fe-93e6-11e8-8617-0444d5ac532a.png)

![image](https://user-images.githubusercontent.com/11845561/43375193-1ec0155c-93e6-11e8-8c05-0164356c986d.png)

![image](https://user-images.githubusercontent.com/11845561/43379262-205e1018-93fe-11e8-9a44-c4dbaee39366.png)

![image](https://user-images.githubusercontent.com/11845561/43379389-c244093c-93fe-11e8-827e-80d13a0b0f8c.png)

![image](https://user-images.githubusercontent.com/11845561/43557497-71cd3844-9637-11e8-813e-8580dff0bbf8.png)

**Comment by niuyongjie** [comment]
this issue was fixed
