### ISSUE TITLE
bundle install failed.

### ISSUE THREAD

**Issue by MagicVin** [kaiyuanshe/kcoin#86]
这个https://mirrors.huaweicloud.com/repository/rubygems/ 这个网址我是可以访问的，但是为什么could not fetch? 
## Error output:
vin@vin-ubuntu:~/kcoin/src/web$ sudo bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application
for all non-root users on this machine.
Fetching source index from https://mirrors.huaweicloud.com/repository/rubygems/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://mirrors.huaweicloud.com/repository/rubygems/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://mirrors.huaweicloud.com/repository/rubygems/
##

**Comment by niuyongjie** [comment]
你可以替换本地文件中 gem source的内容为https://gems.ruby-china.com后再进行bundle install

**Comment by MagicVin** [comment]
除了改了gem source ，我还做了：

1. update gem(gem update --system)
2. apt-get install ruby-dev
3. apt-get install libgmp-dev
4. apt-get install libsqlite3-dev

不过升级gem 需要翻墙?

**Comment by niuyongjie** [comment]
> 除了改了gem source ，我还做了：
> 
> 1. update gem(gem update --system)
> 2. apt-get install ruby-dev
> 3. apt-get install libgmp-dev
> 4. apt-get install libsqlite3-dev
> 
> 不过升级gem 需要翻墙?

不需要翻墙，官网的镜像站点在国外。上面给出的是国内的镜像站点，速度上相对快点
